# Generated by Django 4.2.6 on 2023-10-10 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservadebanho',
            name='cliente',
        ),
        migrations.AddField(
            model_name='reservadebanho',
            name='CustomUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CustomUser'),
        ),
    ]
