# Generated by Django 4.2.6 on 2023-10-11 11:04

from django.db import migrations


def atualizar_petshop_reserva(apps, schema_editor):
    Reserva = apps.get_model('base', 'ReservaDeBanhoBase')
    PetShop = apps.get_model('reserva', 'PetShop')
    petshop = PetShop.objects.create(nome='Padrão', rua='Padrão', bairro='Padrão')
    for reserva in Reserva.objects.filter(petshop__isnull=True):
        reserva.petshop = petshop
        reserva.save()
    


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customuser_delete_cliente'),
    ]

    operations = [
        migrations.RunPython(atualizar_petshop_reserva),
    ]
