# Generated by Django 4.2.6 on 2023-10-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Animal',
                'verbose_name_plural': 'Categorias de Animais',
            },
        ),
        migrations.CreateModel(
            name='CategoriaBanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Categoria de Banho')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Categoria de Banho',
                'verbose_name_plural': 'Categorias de Banho',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('telefone2', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75)),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Formulário de Contato',
                'verbose_name_plural': 'Formulários de Contatos',
                'ordering': ['-nome'],
            },
        ),
        migrations.CreateModel(
            name='RacaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=50, verbose_name='Raça do Animal')),
            ],
            options={
                'verbose_name': 'Raça do Animal',
                'verbose_name_plural': 'Raças dos Animais',
            },
        ),
        migrations.CreateModel(
            name='ReservaDeBanhoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoPet', models.CharField(max_length=50, verbose_name='Nome do PET')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('diaDaReserva', models.DateField(verbose_name='Dia da Reserva')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
        ),
    ]
