# Generated by Django 4.2.6 on 2023-10-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='s_online',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
