# Generated by Django 4.2.6 on 2023-10-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customuser_delete_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='finalizado',
            field=models.BooleanField(blank=True, default=False, verbose_name='Finalizado'),
        ),
    ]
